# Generated by Django 5.2.7 on 2025-10-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_high_value_order_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_order_high_value',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_order_high_value',
            field=models.BooleanField(default=True),
        ),
    ]
